config/routes.rb
Rails.application.routes.draw do
  # = PWA =
  get "service-worker" => "pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "pwa#manifest", as: :pwa_manifest

  # = Authenticating =
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource :password, only: [:edit, :update]
  namespace :identity do
    resource :email, only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset, only: [:new, :edit, :create, :update]
  end

  # = Dashboarding =
  root "users/dashboards#show"
  resources :plays, only: :index
  # (Episodes encapsulate an entries with a user and their associated
  # plays/followings/playlists)
  resources :episodes, only: :index
  resource :play_later_playlist, only: :show, as: :play_later, path: "play_later" do
    scope module: :play_later_playlists do
      resources :items, only: :create
    end
  end

  # = Feeds & Entries
  resources :feeds, only: [:index, :show]
  resources :itunes_feeds, only: :show, path: "itunes", param: :apple_id

  resources :entries, only: :show do
    scope module: :entries do
      resources :plays, only: [:create, :update]
      resource :player, only: :show
      resource :table_of_contents, only: :show, path: "toc"
    end
  end

  # = Searching =
  namespace :directories do
    resource :search, only: [:new, :show]
  end

  # = Following & Playing Later =
  scope :list_items, as: :list_items, defaults: {variant: :list_items} do
    resources :feeds, only: [] do
      resource :following, only: [:create, :destroy]
    end

    resource :play_later_playlist, only: [], as: :play_later, path: "play_later" do
      resources :items, only: :destroy, param: :entry_id, controller: "play_later_playlists/items"
    end
  end

  # = Importing =
  resources :opml_imports, only: [:new, :create]
  constraints subdomain: "websub" do
    get "web_subs/:id/feed", to: "web_subs#update", as: :web_sub_feed
    post "web_subs/:web_sub_id/feed", to: "web_subs/feeds#update"
  end

  # = Etc =
  resources :settings, only: :index
  get "blank", to: "application#blank"
end

app/models/episode.rb
# Wrapper around Entry that is tied to a user
class Episode
  include ActiveModel::API
  include Collections

  attr_accessor :entry, :user, :collection

  delegate_missing_to :entry

  def play
    @play ||= collection&.play_for(entry) || entry.play_by(user)
  end

  def play_later_item
    @play_later ||= collection&.play_later_item_for(entry) ||
      entry.play_later_item_for(user)
  end

  def following
    @following ||= collection&.following_for(entry) ||
      entry.feed.following_for(user)
  end
end

app/models/episode/collection.rb
class Episode::Collection
  delegate_missing_to :episodes

  attr_reader :user

  def initialize(entries:, user:, order: {published_at: :desc}, limit: 25)
    @entries = entries.order(order).limit(limit).load
    @user = user
  end

  def more_feeds(method, joins:, order:)
    @more_feeds ||= user
      .send(method)
      .where.not(id: episodes.map(&:feed_id))
      .group(:id)
      .includes(:rss_image)
      .joins(joins)
      .order(order)
      .limit(5)
  end

  def episodes
    @episodes ||= @entries.map { |entry| build_episode(entry) }
  end

  def play_for(entry)
    plays[entry.id] || Play.new({
      entry:, user:,
      elapsed: 0,
      remaining: entry.duration
    }.compact)
  end

  def following_for(entry)
    followings[entry.feed_id] || Following.new(feed: entry.feed, user:)
  end

  def play_later_item_for(entry)
    play_later_items[entry.id] || PlaylistItem.new(entry:, playlist: user.play_later_playlist)
  end

  private

  def build_episode(entry)
    Episode.new(entry:, user:, collection: self)
  end

  def plays
    @plays ||= Play.includes(:entry).where(user:, entry: @entries).map do |play|
      [play.entry_id, play]
    end.to_h
  end

  def followings
    @followings ||= Following.includes(:feed).where(user:, feed: @entries.map(&:feed_id)).map do |following|
      [following.feed_id, following]
    end.to_h
  end

  def play_later_items
    @play_later_items ||= PlaylistItem.includes(:entry).where(playlist: user.play_later_playlist, entry: @entries).map do |play_later_item|
      [play_later_item.entry_id, play_later_item]
    end.to_h
  end
end

app/models/episode/collections.rb
module Episode::Collections
  extend ActiveSupport::Concern

  class_methods do
    def played_by(user, order: "plays.updated_at DESC", limit: 25)
      Episode::Collection.new(
        entries: user.played_entries.includes(feed: [:rss_image]),
        user:,
        order:,
        limit:
      )
    end

    def all(user, order: {published_at: :desc}, limit: 25)
      Episode::Collection.new(
        entries: user.followed_entries.in_latest_feed.includes(feed: [:rss_image]),
        user:,
        order:,
        limit:
      )
    end

    def play_later_for(user, order: "playlist_items.created_at DESC", limit: 25)
      Episode::Collection.new(
        entries: user.play_later_entries.includes(feed: [:rss_image]),
        user:,
        order:,
        limit:
      )
    end

    def belonging_to(user, feed, search_term: nil, order: {published_at: :desc}, limit: 25)
      Episode::Collection.new(
        entries: feed.entries.in_latest_feed.search(search_term),
        user:,
        order:,
        limit:
      )
    end
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  def index
    @episodes = Episode.all(Current.user)
  end
end

app/views/episodes/_actions.html.erb
<menu class="flex space-x-2">
  <li>
    <%= render "episodes/toggle", episode: %>
  </li>
  <li>
    <%= render "play_later_playlists/items/form", play_later_item: episode.play_later_item %>
  </li>
</menu>

app/views/episodes/_description.html.erb
<p class="text-grey-500 dark:text-grey-400 line-clamp-1 break-all">
  <%= truncate strip_tags((episode.summary || episode.description).to_s.gsub("&nbsp;", " ")), length: 140, separator: " " %>
</p>

app/views/episodes/_episode.html.erb
<% list ||= nil %>
<%= render "list_item", title: episode.title, path: entry_path(episode.entry), contain: true, style: "view-transition-name: #{dom_id(episode, list)}; contain: layout;" do |p| %>
  <% p.content_for :kicker, render("episodes/feed", feed: episode.feed) %>

  <div class="flex space-x-4 text-sm font-medium text-grey-500 dark:text-grey-400">
    <%= render "episodes/published_at", published_at: episode.published_at %>
    <%= render "plays/play", play: episode.play %>
  </div>

  <div class="space-y-fl-3xs">
    <%= render "episodes/description", episode: %>
    <%= render "episodes/actions", episode: %>
  </div>

  <% p.content_for :actions do %>
    <div class="flex h-full items-center justify-center">
      <%= render partial: "followings/form", locals: {following: episode.following}, variants: [:list_items] %>
    </div>
  <% end %>
<% end %>

app/views/episodes/_episodes.html.erb
<%# locals: (episodes:, more_feeds: nil) %>

<%= render "list", id: "episodes", partial: "episodes/episode", collection: episodes do |p| %>
  <%= p.content_for :empty, "Recently updated episodes appear here" %>

  <% if more_feeds %>
    <%= render "feeds/covers", feeds: more_feeds do %>
      <%= link_to "Episodes →", episodes_path, data: {turbo_frame: "_top"}, class: "text-sm font-semibold uppercase tracking-wide before:absolute before:inset-0 before:z-10" %>
    <% end %>
  <% end %>
<% end %>

app/views/episodes/_feed.html.erb
<p class="flex items-center text-grey-500 dark:text-grey-400">
  <span class="relative w-6 h-6 shrink-0 mr-2 before:absolute before:inset-0 before:ring-inset before:ring-1 before:ring-black/10 dark:before:ring-white/10">
    <% if feed.image_url %>
      <%= image_tag ExternalImage.url(feed.image_url), alt: "", width: 24, height: 24, loading: :lazy %>
    <% end %>
  </span>
  <span class="truncate"><%= feed.title %></span>
</p>

app/views/episodes/_published_at.html.erb
<p class="flex items-center">
  <%= icon :calendar, solid: true, class: "h-4 w-4 mr-1 text-grey-300 dark:text-grey-600 -translate-y-px" %>
  <%= local_relative_time published_at, type: "date", class: "uppercase" %>
</p>

app/views/episodes/_toggle.html.erb
<%= render(
  "plays/toggle",
  play: episode.play,
  options: ui.button(size: :xs, color: :secondary)
) do %>
  <%= icon :play, class: "group-data-playing:hidden group-data-loading:hidden w-5 h-5 -ml-px mr-1" %>

  <span class="block group-data-playing:hidden group-data-loading:hidden">Play</span>

  <%= icon :pause, class: "hidden group-data-playing:block w-5 h-5 -ml-px mr-1" %>

  <span class="hidden group-data-playing:block group-data-loading:hidden">Pause</span>

  <%= inline_svg_tag "icons/loading.svg", class: "hidden group-data-loading:block group-data-loading:motion-safe:animate-spin w-5 h-5", title: "Loading", aria: true %>
<% end %>

app/views/episodes/index.html.erb
<% @title = "Episodes" %>

<% content_for :nav do %>
  <%= render "respondable_nav", active_when: "heading:invisible" do %>
    <h1 class="truncate text-fl-sm font-semibold motion-safe:turn-enter:animate-enter-fade motion-safe:turn-exit:animate-exit-fade">Episodes</h1>
  <% end %>
<% end %>

<%= render("heading", data: {layout_target: "observable"}, id: "heading") { "Episodes" } %>

<%= turbo_frame_tag :episodes_frame do %>
  <%= render "episodes", episodes: @episodes %>
<% end %>