config/routes.rb
Rails.application.routes.draw do
  # = PWA =
  get "service-worker" => "pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "pwa#manifest", as: :pwa_manifest

  # = Authenticating =
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource :password, only: [:edit, :update]
  namespace :identity do
    resource :email, only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset, only: [:new, :edit, :create, :update]
  end

  # = Dashboarding =
  root "users/dashboards#show"
  resources :plays, only: :index
  # (Episodes encapsulate an entries with a user and their associated
  # plays/followings/playlists)
  resources :episodes, only: :index
  resource :play_later_playlist, only: :show, as: :play_later, path: "play_later" do
    scope module: :play_later_playlists do
      resources :items, only: :create
    end
  end

  # = Feeds & Entries
  resources :feeds, only: [:index, :show]
  resources :itunes_feeds, only: :show, path: "itunes", param: :apple_id

  resources :entries, only: :show do
    scope module: :entries do
      resources :plays, only: [:create, :update]
      resource :player, only: :show
      resource :table_of_contents, only: :show, path: "toc"
    end
  end

  # = Searching =
  namespace :directories do
    resource :search, only: [:new, :show]
  end

  # = Following & Playing Later =
  scope :list_items, as: :list_items, defaults: {variant: :list_items} do
    resources :feeds, only: [] do
      resource :following, only: [:create, :destroy]
    end

    resource :play_later_playlist, only: [], as: :play_later, path: "play_later" do
      resources :items, only: :destroy, param: :entry_id, controller: "play_later_playlists/items"
    end
  end

  # = Importing =
  resources :opml_imports, only: [:new, :create]
  constraints subdomain: "websub" do
    get "web_subs/:id/feed", to: "web_subs#update", as: :web_sub_feed
    post "web_subs/:web_sub_id/feed", to: "web_subs/feeds#update"
  end

  # = Etc =
  resources :settings, only: :index
  get "blank", to: "application#blank"
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def index
  end
end

app/views/settings/_setting.html.erb
<%= render "list_item", title: setting[:title], path: setting[:path], method: setting[:method] do |p| %>
  <% p.content_for :image do %>
    <div class="p-fl-2xs bg-white dark:bg-black group-focus-within:bg-white dark:group-focus-within:bg-black mr-3">
      <%= icon setting[:icon], class: "w-6 h-6" %>
    </div>
  <% end %>
  <div class="text-fl-xs leading-tight text-grey-500 dark:text-grey-400"><%= setting[:details] %></div>
<% end %>

app/views/settings/index.html.erb
<%
items = [
  {
    title: "Import OPML",
    path: new_opml_import_path,
    icon: :"cloud-upload"
  },
  {
    title: "Followed Feeds",
    path: feeds_path,
    icon: :rss
  }
]
account_items = [
  {
    title: "Change Email",
    path: edit_identity_email_path,
    icon: :"at-symbol",
    details: Current.user.email
  },
  {
    title: "Change Password",
    path: edit_password_path,
    icon: :"lock-closed"
  },
  {
    title: "Log Out",
    path: session_path(Current.session),
    icon: :logout,
    method: :delete
  }
]
%>

<% content_for :nav, render("nav_bar") %>

<div class="mt-2 space-y-fl-3xs">
  <%= render partial: "settings/setting", collection: items %>
</div>

<%= render "container" do %>
  <h2 <%= tag.attributes(ui.heading_2, ui.turn).merge(class: "mt-fl-sm mb-fl-2xs") %>>Account</h2>

  <% unless Current.user.verified? %>
    <div class="mb-fl-sm">
      <p class="text-fl-xs flex">
        We emailed instructions to <%= Current.user.email %>. Follow the instructions to confirm your account.
      </p>
      <p><%= button_to "Re-send verification email", identity_email_verification_path, class: "text-fl-xs underline" %></p>
    </div>
  <% end %>
<% end %>

<div class="mt-2 space-y-fl-3xs">
  <%= render partial: "settings/setting", collection: account_items %>
</div>