config/routes.rb
Rails.application.routes.draw do
  # = PWA =
  get "service-worker" => "pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "pwa#manifest", as: :pwa_manifest

  # = Authenticating =
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource :password, only: [:edit, :update]
  namespace :identity do
    resource :email, only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset, only: [:new, :edit, :create, :update]
  end

  # = Dashboarding =
  root "users/dashboards#show"
  resources :plays, only: :index
  # (Episodes encapsulate an entries with a user and their associated
  # plays/followings/playlists)
  resources :episodes, only: :index
  resource :play_later_playlist, only: :show, as: :play_later, path: "play_later" do
    scope module: :play_later_playlists do
      resources :items, only: :create
    end
  end

  # = Feeds & Entries
  resources :feeds, only: [:index, :show]
  resources :itunes_feeds, only: :show, path: "itunes", param: :apple_id

  resources :entries, only: :show do
    scope module: :entries do
      resources :plays, only: [:create, :update]
      resource :player, only: :show
      resource :table_of_contents, only: :show, path: "toc"
    end
  end

  # = Searching =
  namespace :directories do
    resource :search, only: [:new, :show]
  end

  # = Following & Playing Later =
  scope :list_items, as: :list_items, defaults: {variant: :list_items} do
    resources :feeds, only: [] do
      resource :following, only: [:create, :destroy]
    end

    resource :play_later_playlist, only: [], as: :play_later, path: "play_later" do
      resources :items, only: :destroy, param: :entry_id, controller: "play_later_playlists/items"
    end
  end

  # = Importing =
  resources :opml_imports, only: [:new, :create]
  constraints subdomain: "websub" do
    get "web_subs/:id/feed", to: "web_subs#update", as: :web_sub_feed
    post "web_subs/:web_sub_id/feed", to: "web_subs/feeds#update"
  end

  # = Etc =
  resources :settings, only: :index
  get "blank", to: "application#blank"
end

app/models/dashboard.rb
class Dashboard
  def initialize(user)
    @user = user
  end

  def played
    @played ||= Episode.played_by(@user, limit: 3)
  end

  def more_played_feeds
    @more_played_feeds ||= played.more_feeds(
      :played_feeds, joins: :plays, order: "MAX(plays.updated_at) DESC"
    )
  end

  def recently_updated
    @recently_updated ||= Episode.all(@user, limit: 3)
  end

  def more_recently_updated_feeds
    @more_recently_updated_feeds ||= recently_updated.more_feeds(
      :followed_feeds,
      joins: :most_recent_entry,
      order: "MAX(entries.published_at) DESC"
    )
  end

  def play_later
    @play_later ||= Episode.play_later_for(@user, limit: 3)
  end

  def more_play_later_feeds
    @more_play_later_feeds ||= play_later.more_feeds(
      :play_later_feeds,
      joins: :playlist_items,
      order: "MAX(playlist_items.created_at) DESC"
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Hashid::Rails

  has_secure_password

  has_many :email_verification_tokens, dependent: :destroy
  has_many :password_reset_tokens, dependent: :destroy
  has_many :sessions, dependent: :destroy
  has_many :followings, dependent: :destroy
  has_many :plays, dependent: :destroy
  has_many :followed_feeds, through: :followings, source: :feed
  has_many :played_feeds, through: :plays, source: :feed
  has_many :followed_entries, through: :followed_feeds, source: :entries
  has_many :played_entries, through: :plays, source: :entry
  has_one :play_later_playlist
  has_many :play_later_entries, through: :play_later_playlist, source: :entries
  has_many :play_later_feeds, through: :play_later_entries, source: :feed
  has_many :playlists, dependent: :destroy
  has_many :playlisted_items, through: :playlists, source: :items
  has_many :playlisted_feeds, through: :playlists, source: :feeds

  validates(
    :email,
    format: {with: URI::MailTo::EMAIL_REGEXP},
    presence: true,
    uniqueness: true
  )

  validates(
    :password,
    allow_nil: true,
    length: {minimum: 12},
    format: {with: /(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])/}
  )

  before_validation do
    self.email = email&.downcase&.strip
  end

  before_update if: :email_changed? do
    self.verified = false
  end

  after_update if: :password_digest_previously_changed? do
    sessions.where.not(id: Current.session).destroy_all
  end

  def play_later_playlist
    super || create_play_later_playlist!
  end
end

app/controllers/users/dashboards_controller.rb
class Users::DashboardsController < ApplicationController
  def show
    @dashboard = Dashboard.new(Current.user)
  end
end

app/views/users/dashboards/_more.html.erb
<% if feeds.load.any? %>
  <%= render "container" do %>
    <div class="mt-fl-2xs inline-flex items-center relative">
      <ul class="flex mr-2">
        <% feeds.each do |feed| %>
          <li class="-ml-1.5">
            <%= image_tag feed.image_url, width: 24, height: 24, class: "ring-1 ring-white dark:ring-black", alt: "" %>
          </li>
        <% end %>
      </ul>
      <%= yield %>
    </div>
  <% end %>
<% end %>

app/views/users/dashboards/show.html.erb
<% content_for :nav, render("nav_bar") %>

<%= turbo_frame_tag :dashboard do %>
  <%= render "heading", tag_name: :h2 do %>
    <%= link_to "Recently Played", plays_path, data: {turbo_frame: "_top"} %>
  <% end %>
  <%= render "plays/episodes", episodes: @dashboard.played, more_feeds: @dashboard.more_played_feeds %>

  <%= render "heading", tag_name: :h2 do %>
    <%= link_to "Recently Updated", episodes_path, data: {turbo_frame: "_top"} %>
  <% end %>
  <%= render "episodes/episodes", episodes: @dashboard.recently_updated, more_feeds: @dashboard.more_recently_updated_feeds %>

  <%= render "heading", tag_name: :h2 do %>
    <%= link_to "Play Later", play_later_path, data: {turbo_frame: "_top"} %>
  <% end %>
  <%= render "play_later_playlists/episodes", episodes: @dashboard.play_later, more_feeds: @dashboard.more_play_later_feeds %>
<% end %>